# Generated by Django 3.1.3 on 2021-05-26 06:17

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('blood_group', models.CharField(max_length=5)),
                ('area', models.CharField(max_length=50)),
                ('contact', phone_field.models.PhoneField(blank=True, max_length=31)),
            ],
        ),
    ]
