# Generated by Django 3.1.3 on 2021-05-30 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forminp', '0002_auto_20210526_1151'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='donor',
            unique_together={('name', 'contact')},
        ),
    ]
